In [2]:
import pandas as pd

In [3]:
pd.read_csv('final_data.csv')

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,SRS,Seed,MOV,ORtg,DRtg,NRtg,MOV/A,ORtg/A,DRtg/A,NRtg/A
0,Aaron James,SF,25,NOJ,80,NaN,26.5,5.4,10.8,0.497,...,-1.80,7,-1.87,NaN,NaN,NaN,-1.80,NaN,NaN,NaN
1,Fred Saunders,SF,26,NOJ,56,NaN,11.5,1.8,4.2,0.423,...,-1.80,7,-1.87,NaN,NaN,NaN,-1.80,NaN,NaN,NaN
2,Freddie Boyd,SG,27,NOJ,21,NaN,17.3,2.1,5.2,0.400,...,-1.80,7,-1.87,NaN,NaN,NaN,-1.80,NaN,NaN,NaN
3,Gail Goodrich,SG,34,NOJ,81,NaN,31.5,6.4,13.0,0.495,...,-1.80,7,-1.87,NaN,NaN,NaN,-1.80,NaN,NaN,NaN
4,Gus Bailey,SG,26,NOJ,48,NaN,9.4,1.2,2.9,0.424,...,-1.80,7,-1.87,NaN,NaN,NaN,-1.80,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18802,Micah Potter,C,23,DET,3,0.0,10.3,1.7,3.7,0.455,...,-7.36,14,-7.72,106.96,114.67,-7.71,-7.35,107.02,114.36,-7.34
18803,Rodney McGruder,SG,30,DET,51,2.0,14.8,1.9,4.4,0.436,...,-7.36,14,-7.72,106.96,114.67,-7.71,-7.35,107.02,114.36,-7.34
18804,Saben Lee,PG,22,DET,37,0.0,16.3,1.9,4.8,0.390,...,-7.36,14,-7.72,106.96,114.67,-7.71,-7.35,107.02,114.36,-7.34
18805,Saddiq Bey,SF,22,DET,82,82.0,33.0,5.5,13.9,0.396,...,-7.36,14,-7.72,106.96,114.67,-7.71,-7.35,107.02,114.36,-7.34
18806,Trayvon Palmer,SG,27,DET,1,0.0,17.0,0.0,1.0,0.000,...,-7.36,14,-7.72,106.96,114.67,-7.71,-7.35,107.02,114.36,-7.34